name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B verify dependency:tree -DoutputFile=dependency-tree.txt

      - name: Submit dependency graph
        uses: advanced-security/maven-dependency-submission-action@v2
        with:
          # Workaround for depgraph plugin issue
          dependency-tree-file: dependency-tree.txt